### ISSUE TITLE
Breaks on exotic names

### ISSUE THREAD

**Issue by Firesphere** [richardsjoqvist/silverstripe-localdate#10]
Exotic locales breaks this module causing an error 500 (e.g. fy-NL code)

**Comment by richardsjoqvist** [comment]
Do you have a locale file I can test this with?

**Comment by Firesphere** [comment]
My locale at home is Frisian, code fy-NL, which breaks.

**Comment by Firesphere** [comment]
Any news on this?

**Comment by richardsjoqvist** [comment]
Hello

Sorry, no. I simply do not have any time to investigate this. You are welcome to create a pull request if you manage to remedy the problem and I will review it when time permits.

// Richard
––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––
Richard Sjöqvist   Spiro Kommunikation   spiro.se <http://spiro.se/>   richard@spiro.se <mailto:richard@spiro.se>   031-712 99 85

**Comment by Firesphere** [comment]
Ok, no problem. I'll try to make some time for it. But I'm short on time as well ;)
