### ISSUE TITLE
Composer Installer name

### ISSUE THREAD

**Issue by NobrainerWeb** [richardsjoqvist/silverstripe-localdate#7]
Thx for this module.

Small feature request, can you add
"extra": {
	"installer-name": "localdate"
}

to you composer.json file - so the module will install as localdate and not silverstripe-localdate. Just like to keep the foldernames short :-)

**Comment by richardsjoqvist** [comment]
Sorry, this will create issues for me. You'll need to fork.

**Comment by micschk** [comment]
Would a block like this help?
```
"extra": {
		"installer-name": "localdate",
		"replaces": "silverstripe-localdate"
}
```

**Comment by richardsjoqvist** [comment]
It might, but I don't have the time required to verify it. The module has been used a lot on many installations, so I would need to go through all those to verify it would not be a problem for each of them, which would amount to a lot of time for - as I see it - little to no gain. If you really need a shorter name I recommend a fork. You might also be able to specify a different installpath in your composer.json, but that is uncharted territory for me. Here's something I found on stack for example, it might help (?): http://stackoverflow.com/questions/11883374/how-to-specify-composer-install-path
